### ISSUE TITLE
Bulk download

### ISSUE THREAD

**Issue by nicholasday** [HackNC/resume-parser#2]
Useful for making a zip
* https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.write

guide
* use search term / no search term
* get all rows from db or ones that match id
* use zipfile to make an archive
* give that to user

**Comment by jakes44** [comment]
Button needs stylized, but download as zip working see https://github.com/HackNC/resume-parser/commit/1d7bbc72e6978aee915dd693218030ce02af4ae3
